
INSERT INTO Exercises Values
('Arms', 'Bench Dip', 'Strength'),
('Arms', 'Bench Press - Close Grip (Barbell)', 'Strength'),
('Arms', 'Bicep Curl (Barbell)', 'Strength'),
('Arms', 'Bicep Curl (Cable)', 'Strength'),
('Arms', 'Bicep Curl (Dumbell)', 'Strength'),
('Arms', 'Bicep Curl (Machine)', 'Strength'),
('Arms', 'Cable Kickback', 'Strength'),
('Arms', 'Cable Pushdowns', 'Strength'),
('Arms', 'Concentration Curl (Dumbell)', 'Strength'),
('Arms', 'Hammer Curl (Band)', 'Strength'),
('Arms', 'Hammer Curl (Cable)', 'Strength'),
('Arms', 'Hammer Curl (Dumbbell)', 'Strength'),
('Arms', 'Incline Curl (Dumbbell)', 'Strength'),
('Arms', 'Preacher Curl (Barbell)', 'Strength'),
('Arms', 'Preacher Curl (Dumbbell)', 'Strength'),
('Arms', 'Preacher Curl (Machine)', 'Strength'),
('Arms', 'Reverse Curl (Band)', 'Strength'),
('Arms', 'Reverse Curl (Dumbbell)', 'Strength'),
('Arms', 'Reverse Curl (Barbell)', 'Strength'),
('Arms', 'Reverse Grip Concentration Curl (Dumbbell)', 'Strength'),
('Arms', 'Seated Palm Up Wrist Curl (Dumbbell)', 'Strength'),
('Arms', 'Skullcrusher (Barbell)', 'Strength'),
('Arms', 'Skullcrusher (Dumbbell)', 'Strength'),
('Arms', 'Triceps Dip', 'Strength'),
('Arms', 'Triceps Dip (Assisted)', 'Strength'),
('Arms', 'Triceps Extension', 'Strength'),
('Arms', 'Triceps Extension (Barbell)', 'Strength'),
('Arms', 'Triceps Extension (Cable)', 'Strength'),
('Arms', 'Triceps Extension (Dumbbell)', 'Strength'),
('Arms', 'Triceps Extension (Machine)', 'Strength'),
('Arms', 'Triceps Pushdown (Cable - Straight)', 'Strength'),
('Arms', 'Upright Row (Cable)', 'Strength'),
('Arms', 'Wrist Roller', 'Strength')


