
INSERT INTO Exercises Values
('Back', 'Back Extension', 'Strength'),
('Back', 'Back Extension (Machine)', 'Strength'),
('Back', 'Bent Over One Arm Row (Dumbbell)', 'Strength'),
('Back', 'Bent Over Row (Band)', 'Strength'),
('Back', 'Bent Over Row (Barbell)', 'Strength'),
('Back', 'Bent Over Row (Dumbbell)', 'Strength'),
('Back', 'Bent Over Row - Underhand (Barbell)', 'Strength'),
('Back', 'Chin Up', 'Strength'),
('Back', 'Chin Up (Assisted)', 'Strength'),
('Back', 'Deadlift', 'Strength'),
('Back', 'Good Morning (Barbell)', 'Strength'),
('Back', 'Incline Row (Dumbbell)', 'Strength'),
('Back', 'Inverted Row (Bodyweight)', 'Strength'),
('Back', 'Iso-Lateral Row (Machine)', 'Strength'),
('Back', 'Kneeling Pulldown (Cable)', 'Strength'),
('Back', 'Lat Pulldown (Cable)', 'Strength'),
('Back', 'Lat Pulldown (Machine)', 'Strength'),
('Back', 'Lat Pulldown (Single Arm)', 'Strength'),
('Back', 'Lat Pulldown - Underhand (Cable)', 'Strength'),
('Back', 'Lat Pulldown - Underhand (Band)', 'Strength'),
('Back', 'Lat Pulldown - Wide Grip (Cable)', 'Strength'),
('Back', 'Pendlay Row (Barbell)', 'Strength'),
('Back', 'Pull Up', 'Strength'),
('Back', 'Pull Up (Assisted)', 'Strength'),
('Back', 'Pull Up (Band)', 'Strength'),
('Back', 'Rack Pull (Barbell)', 'Strength'),
('Back', 'Romanian Deadlift (Barbell)', 'Strength'),
('Back', 'Seated Row (Cable)', 'Strength'),
('Back', 'Seated Row (Machine)', 'Strength'),
('Back', 'Seated Wide-Grip Row (Cable)', 'Strength'),
('Back', 'Shrug (Machine)', 'Strength'),
('Back', 'Shrug (Smith Machine)', 'Strength'),
('Back', 'Stiff Leg Deadlift (Barbell)', 'Strength'),
('Back', 'Sumo Deadlift (Barbell)', 'Strength'),
('Back', 'T Bar Row', 'Strength'),
('Back', 'Upright Row (Barbell)', 'Strength'),
('Back', 'Wide Pull Up', 'Strength')

