
INSERT INTO Exercises Values
('Chest', 'Around the World', 'Strength'),
('Chest', 'Bench Press (Barbell)', 'Strength'),
('Chest', 'Bench Press (Cable)', 'Strength'),
('Chest', 'Bench Press (Dumbbell)', 'Strength'),
('Chest', 'Bench Press (Smith Machine)', 'Strength'),
('Chest', 'Bench Press - Wide Grip (Barbell)', 'Strength'),
('Chest', 'Cable Crossover', 'Strength'),
('Chest', 'Chest Dip', 'Strength'),
('Chest', 'Chest Dip (Assisted)', 'Strength'),
('Chest', 'Chest Fly', 'Strength'),
('Chest', 'Chest Fly (Band)', 'Strength'),
('Chest', 'Chest Fly (Dumbbell)', 'Strength'),
('Chest', 'Chest Press (Band)', 'Strength'),
('Chest', 'Chest Press (Machine)', 'Strength'),
('Chest', 'Decline Bench Press (Barbell)', 'Strength'),
('Chest', 'Decline Bench Press (Dumbbell)', 'Strength'),
('Chest', 'Decline Bench Press (Smith Machine)', 'Strength'),
('Chest', 'Incline Bench Press (Barbell)', 'Strength'),
('Chest', 'Incline Bench Press (Cable)', 'Strength'),
('Chest', 'Incline Bench Press (Smith Machine)', 'Strength'),
('Chest', 'Incline Chest Fly (Dumbbell)', 'Strength'),
('Chest', 'Incline Chest Press (Machine)', 'Strength'),
('Chest', 'Iso-Lateral Chest Press (Machine)', 'Strength'),
('Chest', 'Pec Deck (Machine)', 'Strength'),
('Chest', 'Pullover (Dumbbell)', 'Strength'),
('Chest', 'Push Up', 'Strength'),
('Chest', 'Push Up (Band)', 'Strength'),
('Chest', 'Push Up (Knees)', 'Strength')