
INSERT INTO Exercises Values
('Core', 'Ab Wheel', 'Strength'),
('Core', 'Bicycle Crunch', 'Strength'),
('Core', 'Cable Cruch', 'Strength'),
('Core', 'Cable Twist', 'Strength'),
('Core', 'Cross Body Crunch', 'Strength'),
('Core', 'Crunch', 'Strength'),
('Core', 'Crucnch (Machine)', 'Strength'),
('Core', 'Crunch (Stability Ball)', 'Strength'),
('Core', 'Decline Crunch', 'Strength'),
('Core', 'Flat Knee Raise', 'Strength'),
('Core', 'Hanging Leg Raise', 'Strength'),
('Core', 'Jackknife Sit Up', 'Strength'),
('Core', 'Knees to Elbows', 'Strength'),
('Core', 'Oblique Crunch', 'Strength'),
('Core', 'Plank', 'Strength'),
('Core', 'Reverse Crunch', 'Strength'),
('Core', 'Reverse Plank', 'Strength'),
('Core', 'Russian Twist', 'Strength'),
('Core', 'Side Bend (Band)', 'Strength'),
('Core', 'Side Bend (Cable)', 'Strength'),
('Core', 'Side Bend (Dumbbell)', 'Strength'),
('Core', 'Side Plank', 'Strength'),
('Core', 'Sit Up', 'Strength'),
('Core', 'Superman', 'Strength'),
('Core', 'Toes to Bar', 'Strength'),
('Core', 'V Up', 'Strength')