
INSERT INTO Exercises Values
('Legs', 'Box Squat (Barbell)', 'Strength'),
('Legs', 'Bulgarian Split Squat', 'Strength'),
('Legs', 'Cable Pull Through', 'Strength'),
('Legs', 'Calf Press on Leg Press', 'Strength'),
('Legs', 'Calf Press on Seated Leg Press', 'Strength'),
('Legs', 'Deadlift  (Band)', 'Strength'),
('Legs', 'Deadlift (Dumbbell)', 'Strength'),
('Legs', 'Deadlift (Smith Machine)', 'Strength'),
('Legs', 'Deficit Deadlift (Barbell)', 'Strength'),
('Legs', 'Front Squat (Barbell)', 'Strength'),
('Legs', 'Goblet Squat (Kettlebell)', 'Strength'),
('Legs', 'Hack Squat', 'Strength'),
('Legs', 'Hack Squat (Barbell)', 'Strength'),
('Legs', 'Hip Abductor (Machine)', 'Strength'),
('Legs', 'Hip Adductor (Machine)', 'Strength'),
('Legs', 'Hip Thrust (Barbell)', 'Strength'),
('Legs', 'Hip Thrust (Bodyweight)', 'Strength'),
('Legs', 'Jump Squat', 'Strength'),
('Legs', 'Leg Extension (Machine)', 'Strength'),
('Legs', 'Leg Press', 'Strength'),
('Legs', 'Lunge (Barbell)', 'Strength'),
('Legs', 'Lunge (Bodyweight)', 'Strength'),
('Legs', 'Lunge (Dumbbell)', 'Strength'),
('Legs', 'Lying Leg Curl (Machine)', 'Strength'),
('Legs', 'Mountain Climber', 'Strength'),
('Legs', 'Pistol Squat', 'Strength'),
('Legs', 'Romanian Deadlift (Dumbbell)', 'Strength'),
('Legs', 'Seated Calf Raise (Plate Loaded)', 'Strength'),
('Legs', 'Seated Leg Curl (Machine)', 'Strength'),
('Legs', 'Seated Leg Press (Machine)', 'Strength'),
('Legs', 'Single Leg Bridge', 'Strength'),
('Legs', 'Squat (Band)', 'Strength'),
('Legs', 'Squat (Barbell)', 'Strength'),
('Legs', 'Squat (Bodyweight)', 'Strength'),
('Legs', 'Squat (Dumbbell)', 'Strength'),
('Legs', 'Squat (Machine)', 'Strength'),
('Legs', 'Squat (Smith Machine)', 'Strength'),
('Legs', 'Standing Calf Raise (Barbell)', 'Strength'),
('Legs', 'Standing Calf Raise (Bodyweight)', 'Strength'),
('Legs', 'Standing Calf Raise (Dumbbell)', 'Strength'),
('Legs', 'Standing Calf Raise (Machine)', 'Strength'),
('Legs', 'Standing Calf Raise (Smith Machine)', 'Strength'),
('Legs', 'Step-up', 'Strength'),
('Legs', 'Stiff Leg Deadlift (Dumbbell)', 'Strength'),
('Legs', 'Straight Leg Deadlift (Band)', 'Strength'),
('Legs', 'Trap Bar Deadlift', 'Strength'),
('Legs', 'Zercher Squat (Barbell)', 'Strength')






